### Получение списка авторов

GET localhost/authors?page=0
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMCIsInJvbGUiOiJBRE1JTiIsInN0YXRlIjoiQ09ORklSTUVEIiwiZW1haWwiOiJzaWRpa292Lm1hcnNlbEBnbWFpbCJ9.8OnkfAU5L0AvEUfH6Acm8Yyz-KePfezE2ly8rQ_zeBU

### Добавление автора

POST localhost/authors/add
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMCIsInJvbGUiOiJBRE1JTiIsInN0YXRlIjoiQ09ORklSTUVEIiwiZW1haWwiOiJzaWRpa292Lm1hcnNlbEBnbWFpbCJ9.8OnkfAU5L0AvEUfH6Acm8Yyz-KePfezE2ly8rQ_zeBU
Content-Type: application/json

{
  "firstName": "sam1e",
  "lastName": "same"
}

### Обновление автора

PUT localhost/authors/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMCIsInJvbGUiOiJBRE1JTiIsInN0YXRlIjoiQ09ORklSTUVEIiwiZW1haWwiOiJzaWRpa292Lm1hcnNlbEBnbWFpbCJ9.8OnkfAU5L0AvEUfH6Acm8Yyz-KePfezE2ly8rQ_zeBU
Content-Type: application/json

{
  "firstName" : "Александр",
  "lastName": "Пушкин"
}


### Добавление продукта

POST localhost/product/add
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMCIsInJvbGUiOiJBRE1JTiIsInN0YXRlIjoiQ09ORklSTUVEIiwiZW1haWwiOiJzaWRpa292Lm1hcnNlbEBnbWFpbCJ9.8OnkfAU5L0AvEUfH6Acm8Yyz-KePfezE2ly8rQ_zeBU
Content-Type: application/json

{
  "title": "Каблуки",
  "description": "гучи",
  "price": "400 рублей",
  "authorId":1
}

### Получение продукта по его идентификатору

GET localhost/product/2

### Получение токена

POST localhost/login
Content-Type: application/json

{
  "email": "sasha@gmail.com",
  "password": "Evkalipt"
}